/**
 * The icon picker's shelves, and the words each icon answers to — plain data, so a test can hold every icon the app
 * draws to exactly one shelf and the search to the words people actually type (English and Indonesian both).
 */

export interface IconSection {
  title: string;
  keys: readonly string[];
}

export const ICON_SECTIONS: readonly IconSection[] = [
  {
    title: 'Food & drink',
    keys: ['utensils', 'utensils-crossed', 'coffee', 'cup-soda', 'beer', 'wine', 'pizza', 'soup', 'sandwich', 'ice-cream-cone', 'cake', 'chef-hat', 'shopping-basket', 'store', 'egg', 'fish', 'beef', 'drumstick', 'apple', 'carrot', 'cookie', 'cooking-pot', 'hamburger', 'shrimp', 'salad', 'croissant', 'donut', 'cupcake', 'candy', 'ice-cream-bowl', 'banana', 'grape', 'wheat', 'leafy-green', 'martini'],
  },
  { title: 'Transport', keys: ['car', 'car-taxi-front', 'bus', 'bus-front', 'train-front', 'bike', 'ship', 'fuel', 'circle-parking', 'wrench', 'footprints', 'truck', 'motorbike', 'road', 'square-parking', 'car-front', 'car-battery', 'tickets-plane', 'luggage', 'plane-takeoff', 'tram-front', 'sailboat'] },
  {
    title: 'Home & bills',
    keys: ['house', 'building', 'building-2', 'key-round', 'sofa', 'paint-roller', 'hammer', 'spray-can', 'washing-machine', 'bath', 'zap', 'flame', 'droplets', 'wifi', 'smartphone', 'trash-2', 'shield', 'receipt', 'mail', 'repeat', 'glass-water', 'tv', 'refrigerator', 'lamp', 'armchair', 'sprout', 'plug', 'brush-cleaning', 'air-vent', 'lightbulb', 'fan', 'heater', 'shower-head', 'toilet', 'house-plug', 'house-wifi', 'houses', 'plant-pot', 'recycle', 'broom-sparkles', 'soap-dispenser-droplet', 'microwave', 'drill', 'paint-bucket', 'fence', 'key'],
  },
  {
    title: 'Health & care',
    keys: ['heart-pulse', 'stethoscope', 'pill', 'pill-bottle', 'clipboard-plus', 'eye', 'siren', 'shield-plus', 'shield-check', 'shield-alert', 'heart-handshake', 'dumbbell', 'sparkles', 'scissors', 'flower-2', 'message-circle-heart', 'brain', 'cigarette', 'syringe', 'hospital', 'glasses', 'bandage', 'toothbrush', 'tablets', 'thermometer', 'briefcase-medical', 'test-tube', 'microscope'],
  },
  { title: 'Shopping', keys: ['shopping-bag', 'shopping-cart', 'shirt', 'watch', 'gem', 'laptop', 'cpu', 'blocks', 'book', 'package'] },
  {
    title: 'Money',
    keys: ['wallet', 'banknote', 'credit-card', 'piggy-bank', 'hand-coins', 'landmark', 'percent', 'badge-percent', 'trending-up', 'chart-line', 'chart-column', 'circle-plus', 'arrow-left-right', 'gavel', 'file-check', 'id-card', 'coins', 'target', 'wallet-cards', 'banknote-arrow-up', 'banknote-arrow-down', 'vault', 'ticket-percent', 'tags', 'receipt-text', 'file-signature', 'scroll-text'],
  },
  {
    title: 'Fun & travel',
    keys: ['plane', 'bed', 'map', 'map-pin', 'tent', 'tree-palm', 'ticket', 'film', 'clapperboard', 'gamepad-2', 'music', 'camera', 'drama', 'palette', 'brush', 'party-popper', 'trophy', 'headphones', 'popcorn', 'guitar', 'ferris-wheel', 'roller-coaster', 'tent-tree', 'mountain', 'fishing-rod', 'piano', 'drum', 'dices', 'puzzle', 'volleyball', 'radio'],
  },
  { title: 'Family & pets', keys: ['baby', 'users', 'users-round', 'gift', 'flower', 'hand-heart', 'hand-helping', 'paw-print', 'dog', 'cat', 'church', 'milk', 'moon-star', 'toy-brick', 'backpack', 'notebook-pen', 'school-2', 'balloon', 'ribbon', 'medal', 'handbag', 'book-heart', 'bone', 'bird', 'rabbit', 'turtle'] },
  { title: 'Work & learning', keys: ['briefcase', 'graduation-cap', 'school', 'book-open', 'presentation', 'file-text', 'pen-tool', 'briefcase-business', 'hard-hat', 'laptop-2', 'printer', 'router', 'tablet-smartphone', 'newspaper', 'mic'] },
  { title: 'Other', keys: ['circle-ellipsis', 'circle-help'] },
];

/** Words an icon answers to besides its own name. Lowercase; Indonesian beside English where people would type it. */
export const ICON_WORDS: Readonly<Record<string, readonly string[]>> = {
  utensils: ['makan', 'food', 'restaurant', 'meal', 'eat'],
  'utensils-crossed': ['restaurant', 'restoran', 'dining', 'makan'],
  coffee: ['kopi', 'cafe', 'kafe', 'tea', 'teh'],
  'cup-soda': ['soda', 'drink', 'minum', 'boba', 'es'],
  beer: ['bir', 'bar', 'alcohol', 'drink'],
  wine: ['anggur', 'alcohol', 'bar'],
  pizza: ['fast food', 'snack'],
  soup: ['sup', 'soto', 'bakso', 'noodle', 'mie'],
  sandwich: ['snack', 'bekal', 'lunch', 'roti'],
  'ice-cream-cone': ['es krim', 'dessert', 'sweet'],
  cake: ['kue', 'birthday', 'ulang tahun', 'dessert'],
  'chef-hat': ['cook', 'masak', 'catering', 'katering'],
  'shopping-basket': ['groceries', 'belanja', 'pasar', 'market', 'sembako'],
  car: ['mobil', 'vehicle', 'kendaraan'],
  'car-taxi-front': ['taxi', 'taksi', 'ojek', 'grab', 'gojek', 'ride'],
  bus: ['bis', 'public transport', 'angkot', 'transjakarta'],
  'bus-front': ['bis', 'shuttle', 'antar jemput'],
  'train-front': ['kereta', 'krl', 'mrt', 'train', 'commuter'],
  bike: ['sepeda', 'motor', 'bicycle', 'cycling'],
  ship: ['kapal', 'ferry', 'boat', 'feri'],
  fuel: ['bensin', 'gas', 'petrol', 'bbm', 'pertamina'],
  'circle-parking': ['parkir', 'parking', 'toll', 'tol'],
  wrench: ['bengkel', 'service', 'servis', 'repair', 'maintenance'],
  footprints: ['walk', 'jalan', 'steps'],
  house: ['rumah', 'home', 'household'],
  building: ['gedung', 'apartment', 'apartemen', 'office'],
  'building-2': ['property', 'properti', 'apartment'],
  'key-round': ['rent', 'sewa', 'kos', 'kost'],
  sofa: ['furniture', 'perabot', 'decor'],
  'paint-roller': ['paint', 'cat', 'renovation', 'renovasi'],
  hammer: ['tukang', 'repair', 'perbaikan', 'tools'],
  'spray-can': ['cleaning', 'bersih', 'supplies'],
  'washing-machine': ['laundry', 'cuci', 'mesin cuci'],
  bath: ['mandi', 'bathroom', 'toiletries'],
  zap: ['listrik', 'electricity', 'pln', 'power'],
  flame: ['gas', 'elpiji', 'lpg', 'energy'],
  droplets: ['air', 'water', 'pdam'],
  wifi: ['internet', 'indihome', 'broadband'],
  smartphone: ['pulsa', 'phone', 'hp', 'mobile', 'data'],
  'trash-2': ['sampah', 'waste', 'garbage'],
  shield: ['security', 'keamanan', 'satpam'],
  receipt: ['bill', 'tagihan', 'tax', 'pajak'],
  mail: ['pos', 'post', 'postal', 'letter'],
  repeat: ['subscription', 'langganan', 'recurring'],
  'heart-pulse': ['health', 'sehat', 'kesehatan', 'medical'],
  stethoscope: ['doctor', 'dokter', 'clinic', 'klinik'],
  pill: ['obat', 'medicine', 'vitamin', 'supplement'],
  'pill-bottle': ['apotek', 'pharmacy', 'obat'],
  'clipboard-plus': ['check up', 'medical', 'lab'],
  eye: ['mata', 'glasses', 'kacamata', 'optik'],
  siren: ['emergency', 'darurat', 'ambulance'],
  'shield-plus': ['insurance', 'asuransi', 'bpjs'],
  'shield-check': ['insurance', 'asuransi', 'protection'],
  'shield-alert': ['insurance', 'asuransi', 'critical'],
  'heart-handshake': ['life insurance', 'asuransi jiwa', 'care'],
  dumbbell: ['gym', 'fitness', 'olahraga', 'sport'],
  sparkles: ['beauty', 'cantik', 'skincare', 'personal care'],
  scissors: ['haircut', 'potong rambut', 'salon', 'barber'],
  'flower-2': ['spa', 'wellness', 'massage', 'pijat'],
  'message-circle-heart': ['therapy', 'terapi', 'counselling', 'konseling'],
  brain: ['mind', 'self development', 'mental'],
  cigarette: ['rokok', 'smoke', 'vape'],
  'shopping-bag': ['belanja', 'shopping', 'mall'],
  'shopping-cart': ['cart', 'keranjang', 'supermarket', 'groceries', 'belanja bulanan'],
  cpu: ['tech', 'electronics', 'elektronik', 'gadget', 'komputer', 'computer', 'chip'],
  shirt: ['baju', 'clothes', 'pakaian', 'fashion', 'laundry'],
  watch: ['jam', 'accessories', 'aksesoris'],
  gem: ['perhiasan', 'jewelry', 'wedding', 'nikah'],
  laptop: ['komputer', 'computer', 'electronics', 'elektronik', 'gadget'],
  blocks: ['toys', 'mainan', 'lego'],
  book: ['buku', 'books', 'reading'],
  package: ['paket', 'delivery', 'takeaway', 'online'],
  wallet: ['dompet', 'cash', 'uang saku', 'pocket money'],
  banknote: ['uang', 'money', 'salary', 'gaji', 'cash'],
  'credit-card': ['kartu kredit', 'card', 'kartu', 'debit'],
  'piggy-bank': ['tabungan', 'savings', 'nabung'],
  'hand-coins': ['zakat', 'infaq', 'donation', 'sedekah'],
  landmark: ['bank', 'government', 'pemerintah', 'tax', 'pajak'],
  percent: ['interest', 'bunga', 'rate'],
  'badge-percent': ['fee', 'biaya', 'admin', 'cashback', 'diskon', 'discount'],
  'trending-up': ['investment', 'investasi', 'saham', 'stocks'],
  'chart-line': ['gains', 'profit', 'investment'],
  'chart-column': ['chart', 'bar', 'stocks', 'saham', 'investasi', 'investment'],
  'circle-plus': ['other income', 'lainnya', 'extra'],
  'arrow-left-right': ['transfer', 'kirim'],
  gavel: ['fine', 'denda', 'penalty', 'legal', 'hukum'],
  'file-check': ['document', 'dokumen', 'admin'],
  'id-card': ['membership', 'anggota', 'ktp', 'id'],
  plane: ['travel', 'liburan', 'flight', 'pesawat', 'holiday'],
  bed: ['hotel', 'penginapan', 'sleep', 'villa'],
  map: ['trip', 'field trip', 'wisata'],
  'map-pin': ['activities', 'place', 'tempat', 'tour'],
  tent: ['camping', 'kemah', 'recreation', 'rekreasi'],
  'tree-palm': ['beach', 'pantai', 'bali', 'holiday', 'liburan'],
  ticket: ['tiket', 'concert', 'konser', 'event'],
  film: ['movie', 'film', 'bioskop', 'cinema'],
  clapperboard: ['entertainment', 'hiburan', 'streaming'],
  'gamepad-2': ['game', 'gaming', 'main'],
  music: ['musik', 'spotify', 'lagu', 'song'],
  camera: ['kamera', 'photo', 'foto'],
  drama: ['theatre', 'teater', 'performance', 'pentas'],
  palette: ['art', 'seni', 'lukis', 'club'],
  brush: ['hobby', 'hobi', 'craft', 'kerajinan'],
  'party-popper': ['party', 'pesta', 'celebration', 'perayaan'],
  trophy: ['bonus', 'prize', 'hadiah', 'award'],
  baby: ['bayi', 'anak', 'child', 'kid', 'newborn'],
  users: ['family', 'keluarga', 'relatives', 'saudara'],
  'users-round': ['dependants', 'tanggungan', 'parents', 'orang tua'],
  gift: ['hadiah', 'kado', 'present'],
  flower: ['funeral', 'duka', 'bunga', 'flowers'],
  'hand-heart': ['charity', 'amal', 'donation', 'donasi'],
  'hand-helping': ['help', 'bantuan', 'maid', 'art', 'pembantu', 'services', 'asisten', 'helper', 'nanny', 'babysitter', 'suster', 'sopir'],
  'paw-print': ['pet', 'hewan', 'peliharaan', 'vet'],
  dog: ['anjing', 'pet', 'hewan'],
  cat: ['kucing', 'pet', 'hewan'],
  church: ['gereja', 'masjid', 'mosque', 'worship', 'ibadah', 'religion'],
  briefcase: ['work', 'kerja', 'business', 'bisnis', 'office', 'kantor'],
  'graduation-cap': ['sekolah', 'school', 'education', 'pendidikan', 'kuliah', 'university'],
  school: ['sekolah', 'tuition', 'spp', 'uang sekolah'],
  'book-open': ['textbook', 'buku pelajaran', 'study', 'belajar'],
  presentation: ['course', 'kursus', 'les', 'lesson', 'class'],
  'file-text': ['administration', 'administrasi', 'paperwork'],
  'pen-tool': ['design', 'desain', 'stationery', 'alat tulis', 'freelance'],
  'circle-ellipsis': ['other', 'lainnya', 'misc', 'miscellaneous'],
  'circle-help': ['unknown', 'help'],
  store: ['warung', 'toko', 'pasar', 'minimarket', 'shop'],
  milk: ['susu', 'formula', 'mpasi', 'baby food'],
  egg: ['telur', 'sembako', 'protein'],
  fish: ['ikan', 'seafood', 'lauk'],
  beef: ['daging', 'sapi', 'meat', 'lauk'],
  drumstick: ['ayam', 'chicken', 'lauk', 'fried chicken'],
  apple: ['buah', 'fruit'],
  carrot: ['sayur', 'vegetables', 'veggie'],
  cookie: ['jajan', 'snack', 'camilan', 'biscuit'],
  'cooking-pot': ['masak', 'dapur', 'kitchen', 'cooking'],
  'glass-water': ['galon', 'air minum', 'drinking water', 'aqua'],
  tv: ['televisi', 'streaming', 'netflix', 'tv kabel'],
  refrigerator: ['kulkas', 'fridge', 'appliance', 'elektronik'],
  lamp: ['lampu', 'light', 'furniture'],
  armchair: ['kursi', 'furniture', 'mebel', 'perabot'],
  sprout: ['taman', 'garden', 'tanaman', 'plants'],
  plug: ['listrik', 'token', 'pln', 'electricity'],
  syringe: ['vaksin', 'vaccine', 'suntik', 'imunisasi'],
  hospital: ['rumah sakit', 'rs', 'hospital', 'bpjs'],
  glasses: ['kacamata', 'optik', 'eyewear'],
  bandage: ['p3k', 'first aid', 'plester', 'luka'],
  coins: ['emas', 'gold', 'koin', 'uang receh', 'logam mulia'],
  target: ['tabungan', 'goal', 'tujuan', 'savings'],
  'moon-star': ['zakat', 'sedekah', 'infak', 'umrah', 'haji', 'ramadan', 'lebaran'],
  truck: ['pindahan', 'moving', 'delivery', 'kirim', 'ekspedisi'],
  headphones: ['music', 'musik', 'podcast', 'spotify'],
  popcorn: ['bioskop', 'cinema', 'movie', 'nonton'],
  guitar: ['hobi', 'hobby', 'les musik', 'music lesson'],
  'toy-brick': ['mainan', 'toys', 'lego', 'anak'],
  'brush-cleaning': ['art', 'asisten rumah tangga', 'pembantu', 'maid', 'cleaning', 'bersih-bersih', 'sapu', 'broom'],
  'motorbike': ['motor', 'ojek', 'sepeda motor', 'motorcycle', 'scooter'],
  'toothbrush': ['gigi', 'dentist', 'dokter gigi', 'dental', 'teeth'],
  hamburger: ['burger', 'fast food', 'mcd'],
  shrimp: ['udang', 'seafood'],
  salad: ['sayur', 'healthy', 'diet'],
  croissant: ['roti', 'bakery', 'pastry'],
  donut: ['donat', 'jajan', 'snack'],
  cupcake: ['kue', 'bakery', 'dessert'],
  candy: ['permen', 'sweets', 'jajan'],
  'ice-cream-bowl': ['es krim', 'dessert', 'gelato'],
  banana: ['pisang', 'buah', 'fruit'],
  grape: ['anggur', 'buah', 'fruit'],
  wheat: ['beras', 'rice', 'sembako', 'tepung'],
  'leafy-green': ['sayur', 'vegetables', 'sayuran'],
  martini: ['cocktail', 'bar', 'nightlife'],
  'air-vent': ['ac', 'air conditioner', 'servis ac'],
  lightbulb: ['lampu', 'listrik', 'light'],
  fan: ['kipas', 'kipas angin'],
  heater: ['pemanas', 'water heater'],
  'shower-head': ['kamar mandi', 'bathroom', 'shower'],
  toilet: ['wc', 'toilet', 'kamar mandi', 'sedot wc'],
  'house-plug': ['listrik rumah', 'pln', 'token'],
  'house-wifi': ['internet rumah', 'indihome', 'wifi rumah'],
  houses: ['kos', 'kost', 'sewa', 'rent', 'kontrakan'],
  'plant-pot': ['tanaman', 'pot', 'garden'],
  recycle: ['sampah', 'iuran sampah', 'garbage', 'recycle'],
  'broom-sparkles': ['bersih-bersih', 'cleaning', 'art', 'sapu'],
  'soap-dispenser-droplet': ['sabun', 'toiletries', 'perlengkapan mandi'],
  microwave: ['microwave', 'elektronik', 'appliance'],
  drill: ['renovasi', 'tukang', 'tools', 'bor'],
  'paint-bucket': ['cat', 'renovasi', 'paint'],
  fence: ['pagar', 'renovasi'],
  key: ['kunci', 'sewa', 'rent', 'deposit'],
  road: ['tol', 'toll', 'e-toll', 'jalan'],
  'square-parking': ['parkir', 'parking'],
  'car-front': ['mobil', 'car'],
  'car-battery': ['aki', 'servis mobil', 'battery'],
  'tickets-plane': ['tiket pesawat', 'flight', 'penerbangan'],
  luggage: ['koper', 'travel', 'bagasi'],
  'plane-takeoff': ['penerbangan', 'flight', 'berangkat'],
  'tram-front': ['lrt', 'tram', 'kereta'],
  sailboat: ['perahu', 'boat', 'kapal'],
  tablets: ['vitamin', 'suplemen', 'obat'],
  thermometer: ['demam', 'sakit', 'fever'],
  'briefcase-medical': ['p3k', 'medical kit', 'kotak obat'],
  'test-tube': ['lab', 'cek darah', 'laboratorium'],
  microscope: ['lab', 'diagnostic'],
  'wallet-cards': ['dompet', 'e-wallet', 'kartu'],
  'banknote-arrow-up': ['tarik tunai', 'withdraw', 'uang keluar'],
  'banknote-arrow-down': ['setor', 'deposit', 'uang masuk'],
  vault: ['brankas', 'safe deposit', 'emas', 'tabungan'],
  'ticket-percent': ['voucher', 'promo', 'diskon', 'kupon'],
  tags: ['diskon', 'sale', 'harga'],
  'receipt-text': ['struk', 'nota', 'invoice', 'tagihan'],
  'file-signature': ['kontrak', 'perjanjian', 'notaris', 'contract'],
  'scroll-text': ['tagihan', 'bill', 'dokumen'],
  backpack: ['tas sekolah', 'sekolah', 'school bag'],
  'notebook-pen': ['alat tulis', 'buku tulis', 'school supplies'],
  'school-2': ['sekolah', 'spp', 'tuition'],
  balloon: ['ulang tahun', 'birthday', 'pesta'],
  ribbon: ['hadiah', 'kado', 'donasi'],
  medal: ['lomba', 'prestasi', 'competition'],
  handbag: ['tas', 'bag', 'fashion'],
  'book-heart': ['buku anak', 'storybook', 'dongeng'],
  bone: ['makanan anjing', 'dog food', 'pet food'],
  bird: ['burung', 'pet'],
  rabbit: ['kelinci', 'pet'],
  turtle: ['kura-kura', 'pet'],
  'ferris-wheel': ['taman bermain', 'dufan', 'theme park'],
  'roller-coaster': ['wahana', 'theme park', 'dufan'],
  'tent-tree': ['camping', 'kemah', 'glamping'],
  mountain: ['hiking', 'naik gunung', 'pendakian'],
  'fishing-rod': ['mancing', 'fishing', 'pancing'],
  piano: ['les piano', 'music lesson', 'kursus musik'],
  drum: ['drum', 'band', 'musik'],
  dices: ['board game', 'permainan', 'games'],
  puzzle: ['puzzle', 'mainan', 'hobi'],
  volleyball: ['voli', 'olahraga', 'sports'],
  radio: ['radio', 'audio'],
  'briefcase-business': ['usaha', 'bisnis', 'side business', 'kantor'],
  'hard-hat': ['konstruksi', 'tukang', 'proyek', 'renovasi'],
  'laptop-2': ['laptop', 'kerja', 'komputer'],
  printer: ['printer', 'tinta', 'office', 'print'],
  router: ['router', 'modem', 'internet'],
  'tablet-smartphone': ['gadget', 'tablet', 'hp'],
  newspaper: ['koran', 'berita', 'langganan', 'news'],
  mic: ['podcast', 'karaoke', 'mic'],
};

const words = (key: string): string[] => [key.replace(/-\d+$/, '').replace(/-/g, ' '), ...(ICON_WORDS[key] ?? [])];

/** Whether an icon answers to what was typed: any part of its name or its words, ignoring case and spacing. */
export function iconMatches(key: string, query: string): boolean {
  const q = query.trim().toLowerCase().replace(/\s+/g, ' ');
  if (!q) return true;
  return words(key).some((word) => word.includes(q));
}

/** The shelves with only the icons that answer to `query`, empty shelves dropped. An empty query keeps every one. */
export function searchIcons(query: string): IconSection[] {
  return ICON_SECTIONS.map((section) => ({ title: section.title, keys: section.keys.filter((key) => iconMatches(key, query)) })).filter(
    (section) => section.keys.length > 0,
  );
}
